In [1]:
import numpy as np

In [2]:
stop_words = np.genfromtxt('stop_words_english.txt', dtype=str, encoding='utf-8')

In [3]:
stop_words[:5]

array(['able', 'about', 'above', 'abroad', 'according'], dtype='<U15')

In [4]:
    def text_process(abstract:str):
        return [word.lower() for word in ''.join([char for char in abstract if char != '"']).split() if word not in stop_words]


In [5]:
strs = ["Hello I am Jager", "Hello World", "noob Star", "Hello Hello There", ]
all_in_1 = ' '.join(strs)
print(all_in_1)
all_words = text_process(all_in_1)
all_words

Hello I am Jager Hello World noob Star Hello Hello There


['hello', 'jager', 'hello', 'world', 'noob', 'star', 'hello', 'hello', 'there']

In [6]:
aword = 'hello'
all_words.count(aword)

4

In [7]:
from CountVectorizer import CountVectorizer

In [8]:
vectorizer = CountVectorizer(stop_words=stop_words)

In [9]:
vectorizer.fit(strs)

In [10]:
vectorizer.vocabularies

array([['hello', 4],
       ['world', 1],
       ['there', 1],
       ['star', 1],
       ['noob', 1],
       ['jager', 1]], dtype=object)

In [11]:
vectorizer.transform(strs)

array([[1, 0, 0, 0, 0, 1],
       [1, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 0],
       [2, 0, 1, 0, 0, 0]], dtype=object)

In [12]:
from DataFrame import DataFrame
df = DataFrame()

In [13]:
df.read_csv('trg.csv')

In [14]:
abstracts = df.get_col(2)

In [15]:
vectorizer1 = CountVectorizer(stop_words=stop_words,max_features=1000)

In [16]:
abstracts_all_in_1 = ' '.join(abstracts)
words_abstracts = vectorizer1.text_process(abstracts_all_in_1)

In [17]:
words_abstracts.count('affinity')

99

In [18]:
vectorizer1.fit(abstracts)
vectorizer1.vocabularies

array([['genes', 6396],
       ['sequence', 5183],
       ['gene', 5097],
       ...,
       ['viruses', 64],
       ['untranslated', 63],
       ['global', 63]], dtype=object)

In [19]:
vectorized_abstracts100=vectorizer1.transform(abstracts[:100])

In [20]:
vectorized_abstracts100

array([[2, 0, 1, ..., 0, 0, 0],
       [4, 1, 7, ..., 0, 0, 0],
       [6, 3, 1, ..., 0, 0, 0],
       ...,
       [2, 1, 0, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [4, 4, 0, ..., 0, 0, 0]], dtype=object)

In [21]:
unique = vectorizer1.vocabularies[:10,0]
counts = vectorizer1.vocabularies[:10,1].astype(np.int)

In [22]:
unique

array(['genes', 'sequence', 'gene', 'genome', 'protein', 'amino',
       'proteins', 'sequences', 'acid', 'human'], dtype=object)

In [23]:
counts

array([6396, 5183, 5097, 3728, 3493, 2629, 2518, 2429, 2127, 2049])

In [24]:
np.array([unique, counts],dtype = object)

array([['genes', 'sequence', 'gene', 'genome', 'protein', 'amino',
        'proteins', 'sequences', 'acid', 'human'],
       [6396, 5183, 5097, 3728, 3493, 2629, 2518, 2429, 2127, 2049]],
      dtype=object)

In [25]:
np.transpose(np.array([unique, counts],dtype = object))

array([['genes', 6396],
       ['sequence', 5183],
       ['gene', 5097],
       ['genome', 3728],
       ['protein', 3493],
       ['amino', 2629],
       ['proteins', 2518],
       ['sequences', 2429],
       ['acid', 2127],
       ['human', 2049]], dtype=object)